### PR TITLE
Merge zeppelin scripts

### PR DESCRIPTION
**Pull request by vgazzola**
to use zeppelin.sh --[start|stop] instead of start-zeppelin.sh or stop-zeppelin.sh

### CODE REVIEW

**Comment by vgazzola** [comment]
I would suggest to add refresh.sh as an option too.

**Comment by a-pagano** [comment]
Thanks a lot for the PR! It looks good to me.

**Comment by a-pagano** [comment]
Also, I went ahead and integrated a refresh option to the `zeppelin.sh` script and removed the `refresh.sh` script as per your idea 👍

**Comment by a-pagano** [comment]
Merging if no more comments

**Review by a-pagano — APPROVED** [review]

**Pull request merged**
